# Generated by Django 5.0.6 on 2024-06-04 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('cost', models.FloatField(default=0.0)),
                ('status', models.EmailField(max_length=50)),
                ('start_date', models.DateField(verbose_name=datetime.date(2024, 6, 4))),
            ],
        ),
    ]
