# Generated by Django 5.0.6 on 2025-07-09 20:51

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('cost', models.CharField(default='0.0', max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', null=True, upload_to='images/')),
                ('description', models.CharField(default='description', max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('limit', models.IntegerField(default=15)),
                ('availability', models.IntegerField(default=15)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LUN', 'LUNES'), ('MAR', 'MARTES'), ('MIE', 'MIERCOLES'), ('JUE', 'JUEVES'), ('VIE', 'VIERNES'), ('SAB', 'SABADO')], max_length=3), blank=True, default=list, size=None, verbose_name='Días')),
                ('prueba', models.CharField(blank=True, max_length=50, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Postulado', max_length=50)),
                ('progress', models.FloatField(default=0.0)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'unique_together': {('alumno', 'course')},
            },
        ),
    ]
