# Generated by Django 5.0.6 on 2024-06-04 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image_alter_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 6, 4)),
        ),
    ]
