# Generated by Django 5.0.6 on 2025-07-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='description', max_length=300),
        ),
    ]
