# Generated by Django 5.0.6 on 2024-06-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.CharField(default='0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
