# Generated by Django 5.0.6 on 2025-07-09 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
