# Generated by Django 5.0.6 on 2024-06-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='media/images/'),
        ),
    ]
