# Generated by Django 5.0.6 on 2025-07-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='limit',
        ),
    ]
