# Generated by Django 5.0.6 on 2025-07-09 23:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_availability_remove_course_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='availability',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LUN', 'LUNES'), ('MAR', 'MARTES'), ('MIE', 'MIERCOLES'), ('JUE', 'JUEVES'), ('VIE', 'VIERNES'), ('SAB', 'SABADO')], max_length=3), blank=True, default=list, size=None, verbose_name='Días'),
        ),
        migrations.AddField(
            model_name='course',
            name='limit',
            field=models.IntegerField(default=15),
        ),
    ]
